font = global.smallfont;
text = "THIS MOD IS STILL IN DEVELOPMENT!\nTHINGS IN THIS BUILD HAVE NOT BEEN FINALIZED\nAND ARE SUBJECT TO CHANGE\nALSO NOTE THAT THIS MOD BUILT\nOFF OF AN EGGPLANT DECOMP AND ALOT OF\n FEATURES ARE BEING MANUALLY\nRECODED IN, SO EXPECT SOMETHINGS\n TO BE MISSING FROM THIS BUILD\n ENJOY!";
