targetRoom = 1;
gate_index = 1049;
gatemask_index = 2870;
bgsprite = spr_gate_dungeonBG;
cardmusic = 19;
cardsprite = spr_dungeoncard;
displayname = "Bloodsauce Dungeon";
level = "dungeon";
leveltosave = "dungeon";
