selected_level = 0
selected_world = 0
active = 0
alarm[0] = 30
global.leveltorestart = -4
world_array[0] = "WORLD 1"
world_array[1] = "WORLD 2"
world_array[2] = "WORLD 3"
world_array[3] = "WORLD 4"
world_array[4] = "WORLD 5"
level_array[0][0] = ["ENTRANCE", entrance_1, "entrance"]
level_array[0][1] = ["MEDIEVAL", medieval_1R, "medieval"]
level_array[0][2] = ["RUIN", ruin_1, "ruin"]
level_array[0][3] = ["DUNGEON", dungeon_1, "dungeon"]
level_array[1][0] = ["BADLAND", badland_1, "badland"]
level_array[1][1] = ["WASTEYARD", wasteyard_1, "graveyard"]
level_array[1][2] = ["FUN FARM", farm_1, "farm"]
level_array[1][3] = ["SALOON", saloon_1, "saloon"]
level_array[2][0] = ["COVE", cove_1, "plage"]
level_array[2][1] = ["FOREST", forest_1, "forest"]
level_array[2][2] = ["SPACE", space_1, "space"]
level_array[2][3] = ["GOLF", minigolf_1, "minigolf"]
level_array[3][0] = ["STREET", street_intro, "street"]
level_array[3][1] = ["SEWERS", sewer_1, "sewer"]
level_array[3][2] = ["INDUSTRIAL", industrial_1, "industrial"]
level_array[3][3] = ["FREEZER", freezer_1F, "freezer"]
level_array[4][0] = ["PIZZASCARE", chateau_1R, "chateau"]
level_array[4][1] = ["KIDS PARTY", kidsparty_1, "kidsparty"]
level_array[4][2] = ["WAR", war_1, "war"]
toppin_info[0] = [0, 1527]
toppin_info[1] = [0, 1517]
toppin_info[2] = [0, 1521]
toppin_info[3] = [0, 1511]
toppin_info[4] = [0, 1505]
stickpressed = 0
key_up2 = 0
key_down2 = 0
key_left2 = 0
key_right2 = 0
key_jump2 = 0
audio_stop_all()
