image_speed = 0.35
sprite_index = choose(spr_gerome_idle1, spr_gerome_idle2, spr_gerome_idle3)
x += choose(5, 10, 15, -5, -10, -15)
grabbed = 0
hsp = 0
vsp = 0
grav = 0.5
flash = 1
unpickable = 0
hp = 0
scale_xs = choose(1, -1)
scale_ys = 1
grounded = 1
state = states.normal
playerid = obj_player1
mask_index = spr_player_mask
depth = -5
platformid = noone
hsp_carry = 0
vsp_carry = 0
thrown = 0
