shader_set(global.Pal_Shader)
pal_swap_set(obj_player.spr_palette, obj_player.paletteselect, 0)
draw_sprite_ext(sprite_index, image_index, charx, chary, image_xscale, image_yscale, image_angle, c_white, 1)
draw_sprite_ext(spr_charselectdown, image_index, 448, by2, image_xscale, image_yscale, image_angle, c_white, 1)
draw_sprite_ext(spr_charselectup, image_index, 448, by1, image_xscale, image_yscale, image_angle, c_white, 1)
draw_text_color(textx, texty, chartitle, c_white, c_white, c_white, c_white, 1)
draw_set_font(global.bigfont)
if (fade == true)
    draw_sprite_ext(bg_factory1, 0, 0, 0, 1, 1, 0, c_black, fadealpha)
