text = "THIS IS A WIP DECOMP,\nA BUNCH OF STUFF WILL BE MISSING\nNOR IS IT FINISHED AT THE MOMENT\nPLEASE DO NOT, I REPEAT:\nDO NOT SHARE THIS AT ALL!";
xorigin = 1;
yorigin = 0;
font = global.smallfont;
