pausedmusic = 0
fadeoff = 0
global.music = 0
roomname = 523
arena = 0
global.mu = -4
music = -4
secretmusic = -4
musicID = -4
secretmusicID = -4
pillarmusicID = -4
secret = 0
secretend = 0
pillar_on_camera = 0
prevpillar_on_camera = 0
entrancetheme = badland_7
room_arr = [[peptutorial_1, space_5, minigolf_11, Loadiingroom], [bossroom_1, medieval_10, minigolf_11, Loadiingroom], [dragon_1, badland_9, minigolf_11, Loadiingroom], [tower_1, rm_levelselect, minigolf_11, Loadiingroom], [tower_2, rm_levelselect, minigolf_11, Loadiingroom], [Realtitlescreen, medieval_10, minigolf_11, Loadiingroom], [rm_levelselect, dungeon_5, minigolf_11, Loadiingroom], [entrance_1, entrancetheme, industrial_2, Loadiingroom], [dungeon_1, hub_loadingscreen, wasteyard_6, Loadiingroom], [medieval_1R, ruin_3b, minigolf_11, Loadiingroom], [medieval_2bR, ruin_3b, minigolf_11, dungeon_1], [medieval_3, space_lap, minigolf_11, dungeon_1], [medieval_5, space_lap, minigolf_11, dungeon_1], [medieval_6, farm_9, minigolf_11, dungeon_1], [ruin_1, entrance_1, entrance_6c, Loadiingroom], [ruin_5, entrance_1, entrance_6c, dungeon_1], [ruin_6, entrance_5, entrance_6c, dungeon_1], [badland_1, space_secret4, farm_cube, Loadiingroom], [badland_8, space_secret4, farm_cube, dungeon_1], [badland_9, ruin_treasure, farm_cube, dungeon_1], [badland_mart4, ruin_treasure, farm_cube, dungeon_1], [badland_10, space_secret4, farm_cube, dungeon_1], [forest_1, saloon_2, minigolf_11, Loadiingroom], [forest_G1, saloon_2, minigolf_11, dungeon_1], [forest_G1b, space_8, minigolf_11, Loadiingroom], [forest_5, saloon_2, minigolf_11, dungeon_1], [chateau_1R, wasteyard_6b, minigolf_11, Loadiingroom], [sewer_1, badland_secret3, minigolf_11, Loadiingroom], [freezer_1F, sewer_secret3, minigolf_11, Loadiingroom], [kidsparty_1, editor_entrance, minigolf_11, Loadiingroom], [minigolf_1, ruin_secret1, minigolf_11, Loadiingroom], [industrial_1, saloon_4b, minigolf_11, Loadiingroom], [street_intro, minigolf_1, minigolf_11, Loadiingroom], [farm_1, medieval_6, Disclaimer, Loadiingroom], [space_1, wasteyard_treasure, space_10, Loadiingroom], [wasteyard_1, farm_4b, minigolf_11, Loadiingroom], [saloon_1, saloon_lap, medieval_4, Loadiingroom], [cove_1, farm_12b, minigolf_11, Loadiingroom], [war_1, space_secret1, minigolf_11, Loadiingroom], [strongcold_1, saloon_3b, minigolf_11, Loadiingroom], [characterselect, farm_13, minigolf_11, Loadiingroom], [rm_shhh, farm_11, minigolf_11, Loadiingroom]]
pizzatime = 196
